# TODO: enable when Go 1.13 is available there
# As of 2019/10/04: -buildmode=c-shared not supported on openbsd/amd64

# image: openbsd/latest
# packages:
#     - devel/gmake
#     - devel/llvm
#     - lang/go
# environment:
#     CC: clang
# sources:
#     - https://github.com/radareorg/r2pm
# tasks:
#     - build: |
#         cd r2pm
#         gmake
#     - test: |
#         cd r2pm
#         gmake integration-tests
