name: Go
on:
  pull_request:
    branches: [master]
jobs:

  build:
    name: Build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build the Go binary
      run: make r2pm

  test:
    name: Test
    needs: build

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
    - name: Run unit tests
      run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...

    - name: Initialize the database
      run: ./r2pm --debug init

    - name: Make sure r2dec is present in the database
      run: ./r2pm --debug search dec | grep -q 'converts asm to pseudo-C code'

